version: "3"
services:
      app1:
        container_name: compose-container
        image: xyzweb:v1            #custom image name:tag
        build: .                    #dockerfile location
        ports: 
             - "8080:80"

        volumes:
             - ./volume1:/usr/share/nginx/html/
        
        networks:
             - mynet  # using network which we created in same file
networks:
  mynet: # created custom network
